/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Guardar;
import Model.ContaBancaria;
import Model.ContaCorrente;
import Model.ContaPoupanca;
import Model.Relatorio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class SelectConta extends javax.swing.JFrame {
    boolean sit;
    ArrayList<ContaBancaria> contas=new ArrayList<>();
    /**
     * Creates new form SelectConta
     */
    public SelectConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecionar Conta");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Banco TPC");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Conta", "Historico", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de Conta");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Depositar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Sacar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Transferir");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Relatorio");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor");

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Voltar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addGap(41, 41, 41)
                .addComponent(jButton5)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        Object[] row=new Object[3];
        int k=0;
        if(jTextField1.getText().length()!=0){
            Guardar g=new Guardar();
            String chave=jTextField1.getText();
            for(ContaBancaria c:g.Buscar()){
                if(c instanceof ContaCorrente){
                    sit=true;
                }else{
                    sit=false;
                }
                if(chave.equalsIgnoreCase(c.getNrDeConta())){
                    row[0]=c.getNrDeConta();
                    row[1]=c.getHistorico();
                    row[2]=c.getSaldo();
                    k++;
                    model.addRow(row);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Introduza o numero de conta que deseja pesquisar");
        }
        if(k!=0){
            jTable1.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this,"Conta inexistente, por favor verifique e tente novamente!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int i=jTable1.getSelectedRow();
        if(jTextField2.getText().length()!=0){
            int valor=Integer.parseInt(jTextField2.getText());
            if(sit){
                ContaCorrente contacorrente=new ContaCorrente();
                contacorrente.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contacorrente.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contacorrente.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                contacorrente.depositar(valor);
                Guardar.update(contacorrente);
                model.setValueAt(contacorrente.getSaldo(), i, 2);
            } else{
                ContaPoupanca contapoup=new ContaPoupanca();
                contapoup.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contapoup.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contapoup.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                contapoup.depositar(valor);
                model.setValueAt(contapoup.getSaldo(), i, 2);
                Guardar.update(contapoup);
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Introduza o valor que deseja depositar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int i=jTable1.getSelectedRow();
        if(jTextField2.getText().length()!=0){
            int valor=Integer.parseInt(jTextField2.getText());
            if(sit){
                ContaCorrente contacorrente=new ContaCorrente();
                contacorrente.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contacorrente.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contacorrente.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                contacorrente.sacar(valor);
                Guardar.update(contacorrente);
                model.setValueAt(contacorrente.getSaldo(), i, 2);
            } else{
                ContaPoupanca contapoup=new ContaPoupanca();
                contapoup.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contapoup.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contapoup.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                contapoup.sacar(valor);
                Guardar.update(contapoup);
                model.setValueAt(contapoup.getSaldo(), i, 2);
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Introduza o valor que deseja depositar");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int i=jTable1.getSelectedRow();
        if(jTextField1.getText().length()!=0 && jTextField2.getText().length()!=0){
            String conta=jTextField1.getText();
            double valor=Double.parseDouble(jTextField2.getText());
            Guardar g=new Guardar();
            contas=g.Buscar();
            if(sit){
                ContaCorrente contacorrente=new ContaCorrente();
                contacorrente.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contacorrente.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contacorrente.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                int k=0;
                for(ContaBancaria c:contas){
                    if(conta.equalsIgnoreCase(c.getNrDeConta())){
                        contacorrente.transferir(c, valor);
                        Guardar.update(c);
                        Guardar.update(contacorrente);
                        model.setValueAt(contacorrente.getSaldo(), i, 2);
                        break;
                    }    
                }
            } else{
                ContaPoupanca contapoup=new ContaPoupanca();
                contapoup.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contapoup.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contapoup.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                int k=0;
                for(ContaBancaria c:contas){
                    if(conta.equalsIgnoreCase(c.getNrDeConta())){
                        contapoup.transferir(c, valor);
                        Guardar.update(c);
                        Guardar.update(contapoup);
                        model.setValueAt(contapoup.getSaldo(), i, 2);
                        break;
                    }    
                }
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null,"Introduza o valor que deseja depositar");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Relatorio relat=new Relatorio();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int i=jTable1.getSelectedRow();
        if(sit){
                ContaCorrente contacorrente=new ContaCorrente();
                contacorrente.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contacorrente.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contacorrente.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                relat.gerarRelatorio(contacorrente);
            } else{
                ContaPoupanca contapoup=new ContaPoupanca();
                contapoup.setHistorico(String.valueOf(model.getValueAt(i,1)));
                contapoup.setNrDeConta(String.valueOf(model.getValueAt(i,0)));
                contapoup.setSaldo(Integer.parseInt(String.valueOf(model.getValueAt(i,2))));
                relat.gerarRelatorio(contapoup);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
